CREATE DATABASE IF NOT EXISTS test;

CREATE USER IF NOT EXISTS 'test'@'%' IDENTIFIED BY 'test';
CREATE USER IF NOT EXISTS 'test'@'localhost' IDENTIFIED BY 'test';

GRANT ALL PRIVILEGES ON test.* TO 'test'@'%';
GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost';
FLUSH PRIVILEGES;
